# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBIR', '0002_auto_20161214_0702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CBIRS',
            new_name='CBIRS_IMAGE',
        ),
    ]
