# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBIR', '0003_auto_20161214_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBIRS_1024_Feature',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('value', models.TextField(default='a', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='CBIRS_64_Feature',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('value', models.CharField(default='a', max_length=200)),
            ],
        ),
    ]
